### ISSUE TITLE
Support Conan package

### ISSUE THREAD

**Issue by uilianries** [taocpp/postgres#8]
What?  
Provide Conan package support for this project

Why?  
Distribute taocpp::postgres over Bintray as a package

How?  
- Provide Conan recipe
- Provide Conan test package
- Provide Conan build (CPT)
- Update Travis CI to build and upload Conan package
- Update Appveyor to build Conan package

**Comment by uilianries** [comment]
I found `find_package (PostgreSQL REQUIRED)` at https://github.com/taocpp/postgres/blob/master/taocpp-postgres.cmake#L9

So I suppose libpq is required for this project. We could add libpq as requirement for this package. So the user will not need to solve Postgres lib by itself.

**Comment by uilianries** [comment]
Now we have libpq recipe on Bincrafters' repo: bincrafters/conan-libpq, however it is not on Conan center yet.

IMO we could wait for Conan admin review before to integrate with PEGTL.

**Comment by d-frey** [comment]
Thanks! And I agree we should probably wait for libpq to be available through Conan Center, there is not pressure from our side. In fact, taocpp/postgres still needs more documentation before we can stick a 1.0.0 label on it :)
